DEFAULT_BRANCH: main
JSON_PRETTIER_FILTER_REGEX_EXCLUDE: ".release-please-manifest.json"
MARKDOWN_FILTER_REGEX_EXCLUDE: "CHANGELOG.md"
VALIDATE_ALL_CODEBASE: false
DISABLE: COPYPASTE,SPELL
DISABLE_LINTERS: JSON_V8R,YAML_V8R,REPOSITORY_GITLEAKS,REPOSITORY_SEMGREP,REPOSITORY_CHECKOV,REPOSITORY_DEVSKIM,REPOSITORY_GRYPE,KICS
FILEIO_REPORTER: false
FLAVOR_SUGGESTIONS: false
SHOW_ELAPSED_TIME: true
APPLY_FIXES: all

